#!/bin/sh

root="root"
pkgdir="pkgs"

# list of important packages
pkgs="curl#7.36.0.pkg.tgz
e2fsprogs#1.42.9.pkg.tgz
elinks#0.12pre6.pkg.tgz
extlinux#6.02.pkg.tgz
file#5.17.pkg.tgz
fs.pkg.tgz
hbase.pkg.tgz
ii.pkg.tgz
libarchive#3.1.2.pkg.tgz
linux#3.10.32.pkg.tgz
iproute2#3.14.0.pkg.tgz
mksh#R47.pkg.tgz
pkgtools.pkg.tgz
sbase.pkg.tgz
sdhcp.pkg.tgz
shadow#4.2.1.pkg.tgz
sinit.pkg.tgz
smdev.pkg.tgz
tmux#1.9a.pkg.tgz
ubase.pkg.tgz
vim#7.4.pkg.tgz"

# grab and build pkgtools
git clone git://git.2f30.org/pkgtools
cd pkgtools
make || ( echo "missing libarchive?" 1>&2 && exit 1 )
cd - 1>/dev/null
PATH=$(pwd)/pkgtools:$PATH
export PATH

# prepare root
mkdir -p "$root/var/pkg"
mkdir -p "$pkgdir"

# fetch packages
cd "$pkgdir"
for i in $pkgs; do
	searchpkg "$i" | fetchpkg
done
cd - 1>/dev/null

# install packages
for i in $pkgs; do
	installpkg -p "$root" "$pkgdir/$i"
done
