#!/bin/sh

set -e -x

root="/ns/morpheus"
test x"$1" != x"" && root="$1"
tmpdir="$root/tmp/morpheus_install"
pkgdir="$tmpdir/pkgs"

# list of important packages
pkgs="curl#7.36.0.pkg.tgz
e2fsprogs#1.42.9.pkg.tgz
elinks#0.12pre6.pkg.tgz
extlinux#6.02.pkg.tgz
file#5.17.pkg.tgz
fs.pkg.tgz
hbase.pkg.tgz
ii.pkg.tgz
libarchive#3.1.2.pkg.tgz
linux#3.10.32.pkg.tgz
iproute2#3.14.0.pkg.tgz
mksh#R47.pkg.tgz
pkgtools.pkg.tgz
sbase.pkg.tgz
sdhcp.pkg.tgz
shadow#4.2.1.pkg.tgz
sinit.pkg.tgz
smdev.pkg.tgz
tmux#1.9a.pkg.tgz
ubase.pkg.tgz
vim#7.4.pkg.tgz"

# prepare root
mkdir -p "$root/var/pkg"
mkdir -p "$pkgdir"
mkdir -p "$tmpdir"

# fetch pkgtools in tmpdir
cd "$tmpdir"
pkgtools="pkgtools.pkg.tgz"
if ! test -f "$pkgtools"; then
	wget "http://morpheus.2f30.org/0.0/packages/x86_64/${pkgtools}"
fi
if ! test -d "$tmpdir/bin"; then
	tar -xzf "$pkgtools"
fi
export PATH="$tmpdir/bin:$PATH"

# fetch packages
cd "$pkgdir"
for i in $pkgs; do
	searchpkg "$i" | fetchpkg
done
cd - 1>/dev/null

# install packages
for i in $pkgs; do
	installpkg -r "$root" "$pkgdir/$i"
done

# copy etc/resolv.conf
cp /etc/resolv.conf "$root/etc/resolv.conf"
chmod 644 "$root/etc/resolv.conf"
