#!/bin/sh
#
# you need pkgtools from http://git.2f30.org/pkgtools/

root="root"
pkgdir="pkgs"
# prepare root.
mkdir -p "$root/var/pkg"
mkdir -p "$pkgdir"
# fetch packages.
searchpkg '\.tgz$' | xargs wget -c -P "$pkgdir"
# install
installpkg -p "$root" "$pkgdir/busybox#1.22.1.pkg.tgz"
installpkg -p "$root" "$pkgdir/curl#7.36.0.pkg.tgz"
installpkg -p "$root" "$pkgdir/e2fsprogs#1.42.9.pkg.tgz"
installpkg -p "$root" "$pkgdir/extlinux#6.02.pkg.tgz"
installpkg -p "$root" "$pkgdir/file#5.17.pkg.tgz"
installpkg -p "$root" "$pkgdir/fs.pkg.tgz"
installpkg -p "$root" "$pkgdir/hbase.pkg.tgz"
installpkg -p "$root" "$pkgdir/ii.pkg.tgz"
installpkg -p "$root" "$pkgdir/linux#3.10.32.pkg.tgz"
installpkg -p "$root" "$pkgdir/mksh#R47.pkg.tgz"
installpkg -p "$root" "$pkgdir/pkgtools.pkg.tgz"
installpkg -p "$root" "$pkgdir/sbase.pkg.tgz"
installpkg -p "$root" "$pkgdir/sdhcp.pkg.tgz"
installpkg -p "$root" "$pkgdir/sinit.pkg.tgz"
installpkg -p "$root" "$pkgdir/smdev.pkg.tgz"
installpkg -p "$root" "$pkgdir/tmux#1.9a.pkg.tgz"
installpkg -p "$root" "$pkgdir/ubase.pkg.tgz"
installpkg -p "$root" "$pkgdir/vim#7.4.pkg.tgz"
