#!/bin/sh

if test "$1" != ""; then
	root=$1
else
	root=root
fi

echo -n "Mounting $root/dev... "
sudo mount -o bind /dev $root/dev
echo "done."
echo -n "Mounting $root/dev/pts... "
sudo mount -o bind /dev/pts $root/dev/pts
echo "done."
echo -n "Mounting $root/proc... "
sudo mount -t proc proc $root/proc
echo "done."
echo -n "Mounting $root/sys... "
sudo mount -o bind /sys $root/sys
echo "done."
echo "Chrooting $root..."
sudo chroot $root /bin/sh
echo -n "Unmounting $root/dev/pts... "
sudo umount $root/dev/pts
echo "done."
echo -n "Unmounting $root/dev... "
sudo umount $root/dev
echo "done."
echo -n "Unmounting $root/sys... "
sudo umount $root/sys
echo "done."
echo -n "Unmounting $root/proc... "
sudo umount $root/proc
echo "done."
