#!/bin/bash

# Export important variables for the build scripts
top=$(pwd)
root=$top/root
mirror=http://dl.2f30.org/morpheus-pkgs
export top root mirror

# Create directory hierarchy
rm -rf $root src
mkdir -p $root/{bin,boot,dev,etc,svc,home,root,var,share,devel}
mkdir -p $root/share/man
mkdir -p $root/devel/{include,lib,src}
mkdir -p $root/var/run
mkdir -p $root/dev/shm
mkdir -p $root/{sys,proc}
pushd $root/
ln -s /bin sbin
popd
mkdir -p src
mkdir -p kernel

# Build and install musl-gcc
pushd cross
tar xzf musl-0.9.13.tar.gz
pushd musl-0.9.13
./configure --prefix=$top/cross
make -j2 && make install
popd
popd

PATH=$top/cross/bin:$PATH
export PATH

# Fetch packages
pkglist=$(ls pkgs)
for pkg in $pkglist; do
	export pkg
	. pkgs/$pkg
done

# Fetch kernel
wget -c http://dl.2f30.org/morpheus-pkgs/bzImage -O kernel/bzImage
wget -c http://dl.2f30.org/morpheus-pkgs/bzImage-config -O kernel/bzImage-config

pushd $root
find . | cpio --quiet -H newc -o | gzip -9 -n > ../rootfs.img
popd

echo OK!
