#!/bin/sh
#
# Only meant to be executed from within the stage0 script

fetch() {
	return
}

unpack() {
	return
}

patch() {
	return
}

build() {
	return
}

install() {
	return
}

. $1
(
	fetch
	unpack
	patch
	build
	install
)
