#!/bin/sh
#
# Ensure you've loaded the loop module with max_part=15

dd if=/dev/zero of=morpheus-boot.img bs=128M count=1
fdisk morpheus-boot.img <<< '
o
n
p
1


a
w'

lodev=$(losetup -f --show morpheus-boot.img) || exit 1
partition="$lodev"p1
mkfs.ext4 $partition || exit 1
mount $partition /mnt || exit 1

cp -dar root/* /mnt
extlinux --install /mnt/boot || exit 1

dd if=data/mbr.bin conv=notrunc bs=440 count=1 of=$lodev

umount /mnt
sleep 3
losetup -d $lodev
