#!/bin/sh

if test -z "$1"; then
	echo usage: $0 pkgname 1>&2
	exit 1
fi

# Export important variables for the build scripts
top=$(pwd)
root=$top/root
mirror=http://dl.2f30.org/morpheus-pkgs
export top root mirror

PATH=$top/cross/bin:$PATH
export PATH

./build "$1"
