#!/bin/sh

umask 022

if test -z "$1"; then
	echo usage: $0 pkg... 1>&2
	exit 1
fi

. ./prepare-env

if test "$(uname -m)" != "$arch"; then
	echo You need an $arch host to build morpheus 1>&2
	exit 1
fi

. ./prepare-root
mkdir -p src

while [ $# -gt 0 ]; do
	./build "pkgs/$1"
	shift
done
