#!/bin/sh

vdesock="/tmp/morpheus-vde"

ps -ef | grep vde_switch | grep "sock $vdesock" | grep -v grep > /dev/null || {
    vde_switch -sock "$vdesock" -daemon -mod 660 -group kvm &&
    slirpvde -s "$vdesock" --dhcp --daemon -H '10.1.2.0/24' -L '2223:10.1.2.15:22'
}

qemu-system-x86_64 -enable-kvm -smp 2 -m 1024 -net nic,model=ne2k_pci \
	-net vde,sock="${vdesock}" -kernel root/boot/bzImage -initrd morpheus.img -append "quiet"
