#!/bin/sh

set -e -x

rm -rf root cross morpheus.log
. ./prepare-env
. ./prepare-root

mkdir -p src cross

# Deps list
./build cross-scripts/musl

# Build stage0 packages
pkglist=$(ls pkgs)
for pkg in $pkglist; do
	while read line; do
		if [ $(echo $line | cut -d' ' -f1) != $pkg ]; then
			continue
		fi
		deps=$(echo $line | cut -d' ' -f2-)
		# Build dependencies for package in order
		for d in $deps; do
			./build cross-scripts/$d
		done
	done < DEPS
	./build pkgs/$pkg
done

echo OK!
