#!/bin/sh

set -e -x

rm -rf root cross morpheus.log
. ./prepare-env
. ./prepare-root

mkdir -p src cross

# Deps list
./build cross-scripts/musl

# Build stage0 packages
installed_deps=
pkglist=$(ls pkgs)
for pkg in $pkglist; do
	while read line; do
		if [ $(echo $line | cut -d' ' -f1) != $pkg ]; then
			continue
		fi
		deps=$(echo $line | cut -d' ' -f2-)
		# Build dependencies for package in order
		for d in $deps; do
			install=1
			for i in $installed_deps; do
				if [ $i == $d ]; then
					# If already installed, then skip it
					install=0
					break
				fi
			done
			if [ $install -eq 1 ]; then
				./build cross-scripts/$d
				installed_deps="$installed_deps $d"
			fi
		done
	done < DEPS
	./build pkgs/$pkg
done
