#!/bin/sh
#
# This is the stage0 script, it prepares a basic usable system
# in $root.

rm -rf root morpheus.log

packages="crossmusl
          ncurses
          libevent
          zlib
          tinyxlib
          tinyalsa
          kernel
          kernel-headers
          emul
          busybox
          fs
          make
          man
          mksh
          rsync
          sbase
          sdhcp
          sic
          sinit
          smdev
          syslinux
          tinyxserver
          tmux
          ubase
          uuterm
          tinywm
          xsetroot
          terminus
          dwm
          mpg123
          jupp"

./pkgbuild $packages
