# TODO: update to 1.0.1h
LIB = openssl
DEPS = zlib
INSTALL_LIB = libcrypto.a libssl.a
INSTALL_OTHER1 = `{ls include/openssl/*.h}
INSTALL_OTHER1_DIR = /include/openssl
# NOTE: requires atleast perl and patch as make dependencies.

<$mkbuild/mk.common

openssl:QV:
	# disable fips in the build
	# make sure the man pages are suffixed #302165
	# don't bother building man pages if they're disabled
	sed -i \
		-e '/DIRS/s: fips : :g' \
		-e '/^MANSUFFIX/s:=.*:=ssl:' \
		-e '/^MAKEDEPPROG/s:=.*:=$(CC):' \
		-e '/^MANDIR=/s:=.*:=/share/man:' \
		Makefile.org
	# show the actual commands in the log
	sed -i '/^SET_X/s:=.*:=set -x:' Makefile.shared
	#
	sed -i '1s,^:$,#!/usr/bin/perl,' Configure #141906
	#
	sed -i 's/-DTERMIO/-DTERMIOS/g' Configure
	sed -i 's/defined(linux)/0/' crypto/ui/ui_openssl.c
	# this is asm generated by perl (asm/cast-586.pl) which will cause textrel's that
	# will require musl's dynlinker to mprotect(PROT_EXEC), which is not allowed by grsec.
	sed -i 's@cast-586.o:@c_enc.o:@' Configure
	#
	export CFLAGS="-fPIC -Wa,--noexecstack -fno-strict-aliasing -D_GNU_SOURCE -Wl,-Bsymbolic \
		$optcflags $DEPS_CFLAGS"
	export LDFLAGS="$optldflags $DEPS_LDFLAGS"
	# guess arch
	# NOTE: guess logic in ./config script is weird so set arch here and call
	#       Configure directly.
	sslarch="linux-generic32" # default
	case "$arch" in
	x86_64)
		sslarch="linux-generic64"
		;;
	arm)
		sslarch="linux-armv4"
		;;
	esac
	./Configure "${sslarch}" \
		--prefix="$PREFIX" --openssldir="$PREFIX"/etc/ssl \
		--libdir="$PREFIX"/lib no-dso no-asm zlib enable-md2 $CFLAGS
	# Clean out hardcoded flags that openssl uses
	CFLAG=$(grep ^CFLAG= Makefile | LC_ALL=C sed \
		-e 's:^CFLAG=::' \
		-e 's:-fomit-frame-pointer ::g' \
		-e 's:-O[0-9] ::g' \
		-e 's:-march=[-a-z0-9]* ::g' \
		-e 's:-mcpu=[-a-z0-9]* ::g' \
		-e 's:-m[a-z0-9]* ::g' \
	)
	for mak in Makefile ; do
	sed -i \
		-e "/^CFLAG/s|=.*|=${CFLAG} ${CFLAGS} ${INCLUDES}|" \
		-e "/^SHARED_LDFLAGS=/s|$| ${LDFLAGS}|" \
		"$mak"
	done
	cp crypto/cast/Makefile crypto/cast/Makefile.backup
	# second part of our cast-586 fix: CFLAGS need to be picked up by the makefile.
	sed -i 's@CFLAG=-g@CFLAG=${CFLAG} ${CFLAGS}@' crypto/cast/Makefile
	make -j$nprocs depend
	make -j$nprocs build_libs
