/*----------------------------------------------------------------------------
** This file has been automatically generated by configure any changes in it
** will be lost when you run configure again.
** Instead of modifying definitions here, use the --enable/--disable options
** of the configure script! See ./configure --help for details.
*---------------------------------------------------------------------------*/

#ifndef MPV_CONFIG_H
#define MPV_CONFIG_H

#define CONFIGURATION ""
/*--cc=arm-linux-musleabi-gcc --prefix= --mandir=/share/man --disable-gl --disable-libguess --disable-terminfo --disable-termcap --disable-termios --disable-iconv --disable-lirc --disable-joystick --disable-vm --enable-xf86keysym --disable-dvb --disable-tv --disable-tv-v4l2 --disable-libv4l2 --disable-pvr --disable-smb --disable-libquvi4 --disable-libquvi9 --disable-lcms2 --disable-bluray --disable-dvdread --disable-dvdnav --disable-enca --enable-libass --disable-libpostproc --enable-libavdevice --enable-libavfilter --disable-vapoursynth --disable-jpeg --disable-libcdio --disable-ffmpeg --disable-ladspa --disable-libbs2b --disable-mpg123 --disable-libavresample --disable-libswresample --disable-caca --disable-sdl2 --disable-xv --disable-vdpau --disable-vaapi --disable-vm --enable-xinerama --enable-x11 --disable-wayland --disable-xss --enable-alsa --disable-ossaudio --disable-rsound --disable-sndio --disable-pulse --disable-portaudio --disable-jack --disable-openal --disable-select --enable-shm --disable-lua --disable-encoding --disable-build-man --enable-static"*/

#define MPLAYER_CONFDIR "/etc/mpv"

/* we didn't bother to add actual config checks for this, or they are
   for platforms not supported by this configure script */
#define HAVE_BSD_FSTATFS 0
#define HAVE_LINUX_FSTATFS 0
#define HAVE_VDA_AV_VDA_ALLOC_CONTEXT 0
#define HAVE_VDA_HWACCEL 0
#define HAVE_VDA_LIBAVCODEC_REFCOUNTING 0
#define HAVE_VDA_GL 0
#define HAVE_GL_COCOA 0
#define HAVE_COCOA 0
#define HAVE_COREVIDEO 0
#define HAVE_COREAUDIO 0
#define HAVE_GL_WIN32 0
#define HAVE_DIRECT3D 0
#define HAVE_DSOUND 0
#define HAVE_WASAPI 0
#define HAVE_DOS_PATHS 0
#define HAVE_PRIORITY 0
#define HAVE_GLOB 1
#define HAVE_POSIX_SELECT 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_NANOSLEEP 1
#define HAVE_SDL1 0

#define DEFAULT_CDROM_DEVICE "/dev/cdrom"
#define DEFAULT_DVD_DEVICE   "/dev/dvd"
#define PATH_DEV_DSP "/dev/dsp"
#define PATH_DEV_MIXER "/dev/mixer"


#define HAVE_LIBDL 0
#define HAVE_STDATOMIC 0
#define HAVE_ATOMIC_BUILTINS 0
#define HAVE_SYNC_BUILTINS 0
#define HAVE_ICONV 0
#define HAVE_SYS_SOUNDCARD_H 1
#define HAVE_SOUNDCARD_H 0
#define HAVE_SYS_VIDEOIO_H 0
#define HAVE_TERMINFO 0
#define HAVE_TERMCAP 0
#define HAVE_TERMIOS_H 0
#define HAVE_SYS_TERMIOS_H 0
#define HAVE_TERMIOS 0
#define HAVE_SHM 1
#define HAVE_AUDIO_SELECT 0
#define HAVE_LIBGUESS 0
#define HAVE_LIBSMBCLIENT 0
#define HAVE_LIBQUVI4 0
#define HAVE_LIBQUVI9 0
#define HAVE_LIBQUVI 0
#define HAVE_WAYLAND 0
#define HAVE_X11 1
#define HAVE_XSS 0
#define HAVE_XEXT 0
#define HAVE_XV 1
#define HAVE_VDPAU 0
#define HAVE_VDPAU_HWACCEL 1
#define HAVE_VAAPI 0
#define HAVE_VAAPI_HWACCEL 1
#define HAVE_VAAPI_VPP 0
#define HAVE_VAAPI_GLX 0
#define HAVE_XINERAMA 1
#define HAVE_XF86VM 0
#define HAVE_XF86XK 1
#define HAVE_CACA 0
#define HAVE_DVB 0
#define HAVE_DVBIN 0
#define HAVE_JPEG 0
#define HAVE_GL 0
#define HAVE_GL_X11 0
#define HAVE_GL_WAYLAND 0
#define HAVE_VDPAU_GL_X11 0
#define HAVE_SDL2 0
#define HAVE_OSS_AUDIO 0
#define HAVE_RSOUND 0
#define HAVE_SNDIO 0
#define HAVE_PULSE 0
#define HAVE_PORTAUDIO 0
#define HAVE_JACK 0
#define HAVE_OPENAL 0
#define HAVE_ALSA 1
#define HAVE_LIBBLURAY 0
#define HAVE_DVDREAD 0
#define HAVE_DVDNAV 0
#define HAVE_CDDA 0
#define HAVE_LIBASS 1
#define HAVE_ENCA 0
#define HAVE_ZLIB 0
#define HAVE_MPG123 0
#define HAVE_LADSPA 0
#define HAVE_LIBBS2B 0
#define HAVE_LCMS2 0
#define HAVE_VAPOURSYNTH 0
#define HAVE_FFMPEG 0
#define HAVE_LIBAVRESAMPLE 1
#define HAVE_LIBSWRESAMPLE 0
#define HAVE_AVCODEC_CHROMA_POS_API 0
#define HAVE_AVCOL_SPC_BT2020 1
#define HAVE_AVCODEC_METADATA_UPDATE_SIDE_DATA 0
#define HAVE_AVCODEC_REPLAYGAIN_SIDE_DATA 0
#define HAVE_AV_DISPLAYMATRIX 0
#define HAVE_AVFRAME_METADATA 0
#define HAVE_AVUTIL_QP_API 0
#define HAVE_LIBAVFILTER 1
#define HAVE_LIBAVDEVICE 1
#define HAVE_LIBPOSTPROC 0
#define HAVE_TV 0
#define HAVE_TV_V4L2 0
#define HAVE_AUDIO_INPUT 0
#define HAVE_LIBV4L2 0
#define HAVE_PVR 0
#define HAVE_LUA 0
#define HAVE_JOYSTICK 0
#define HAVE_LIRC 0
#define HAVE_ENCODING 0
#define HAVE_DLOPEN 1
#endif /* MPV_CONFIG_H */
