<$mkbuild/mk.3rdparty

<v.mk
src = libressl-$v
url = http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$v.tar.gz
mkfile = ../libressl.mk

patches = \
	../libressl-entropy-nonsense.patch \
	../libressl-glibc.patch
