#!/bin/sh
#
# Ensure you've loaded the loop module with max_part=15

if test "$2" = ""; then
	echo "Usage: $0 <rootdir> <imgfile>"
	exit
fi
root=$1
img=$2

set -e -x

dd if=/dev/zero of=$img bs=512M count=8
(
cat << EOF
o
n
p
1


a
1
w
EOF
) | fdisk $img

lodev=$(losetup -f --show $img) || exit 1
partition="$lodev"p1
mkfs.ext2 -L MORPHEUS $partition || exit 1
mount $partition /mnt || exit 1
rmdir /mnt/lost+found

fakeroot cp -arP "$root"/* /mnt
extlinux --install /mnt/boot || exit 1

dd if=stuff/mbr.bin of=$lodev conv=notrunc bs=440 count=1
sync

umount /mnt
sleep 3
losetup -d $lodev
